<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="csrf-token" content="{{ csrf_token() }}"><title>eBay ended listing cleanup runner</title><style>body{font-family:system-ui,sans-serif;margin:24px}.panel{border:1px solid #ddd;padding:16px;margin:16px 0}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));gap:8px}.card{background:#f9fafb;border:1px solid #e5e7eb;padding:10px}.card strong{display:block;font-size:1.3rem}pre{background:#f3f4f6;padding:12px;overflow:auto}button{margin:4px;padding:8px 12px}.exports a{display:inline-block;margin:4px 8px 4px 0}.ok{color:#166534}.error{color:#991b1b}</style></head><body>
<div data-marker="{{ $marker }}" data-browser-auto-run-fallback="1">
<h1>eBay listing status audit / local cleanup</h1>
@if(session('runner_message'))<p class="ok">{{ session('runner_message') }}</p>@endif @if(session('runner_error'))<p class="error">{{ session('runner_error') }}</p>@endif
<div class="panel"><h2>Status</h2><div id="grid" class="grid"></div><pre id="results">{{ json_encode($status, JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></div>
<div class="panel"><h2>Akcje</h2>
<form id="startDry" method="post" action="{{ route('admin.tools.ebay.listing-status-audit-runner.start') }}">@csrf<input type="hidden" name="confirm" value="start-ebay-listing-status-audit-runner"><input type="hidden" name="mode" value="dry_run"><label>Batch <input name="batch_size" type="number" value="10" min="1" max="50"></label><label>Delay <input name="delay_seconds" type="number" value="2" min="0"></label><button>Start dry-run</button></form>
<form id="startLive" method="post" action="{{ route('admin.tools.ebay.listing-status-audit-runner.start') }}">@csrf<input type="hidden" name="confirm" value="start-ebay-listing-status-audit-runner"><input type="hidden" name="mode" value="live"><label>Batch <input name="batch_size" type="number" value="10" min="1" max="50"></label><label>Delay <input name="delay_seconds" type="number" value="2" min="0"></label><button>Start live</button></form>
<form id="runNext" method="post" action="{{ route('admin.tools.ebay.listing-status-audit-runner.run-next-batch') }}">@csrf<button>Run next batch</button></form>
<form id="stop" method="post" action="{{ route('admin.tools.ebay.listing-status-audit-runner.stop') }}">@csrf<button>Stop</button></form>
<div class="exports"><h3>Export wyników ostatniego runnera</h3><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results', ['json' => 1, 'status' => 'cleanup_recommended']) }}">Pobierz JSON: cleanup recommended</a><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results.csv', ['status' => 'cleanup_recommended']) }}">Pobierz CSV: cleanup recommended</a><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results', ['json' => 1, 'status' => 'cleaned']) }}">Pobierz JSON: cleaned</a><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results.csv', ['status' => 'cleaned']) }}">Pobierz CSV: cleaned</a><span id="failedSkippedExports" style="display:none"><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results', ['json' => 1, 'status' => 'failed']) }}">Pobierz JSON: failed</a><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results.csv', ['status' => 'failed']) }}">Pobierz CSV: failed</a><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results', ['json' => 1, 'status' => 'skipped']) }}">Pobierz JSON: skipped</a><a href="{{ route('admin.tools.ebay.listing-status-audit-runner.results.csv', ['status' => 'skipped']) }}">Pobierz CSV: skipped</a></span></div><p><a href="{{ route('admin.tools.ebay.listing-status-diagnose', ['part_id' => 927, 'json' => 1]) }}">Diagnose part_id=927 JSON</a></p>
</div></div>
<script>(()=>{const statusUrl=@json(route('admin.tools.ebay.listing-status-audit-runner.status',['json'=>1]));const runUrl=@json(route('admin.tools.ebay.listing-status-audit-runner.run-next-batch'));const csrf=document.querySelector('meta[name="csrf-token"]').content;const keys=['status','mode','total_candidates_at_start','processed','remaining','active_count','ended_count','not_found_count','skipped_count','failed_count','cleanup_recommended_count','cleaned_count'];function render(s){document.getElementById('failedSkippedExports').style.display=((Number(s?.failed_count||0)+Number(s?.skipped_count||0))>0)?'inline':'none';document.getElementById('grid').innerHTML=keys.map(k=>`<div class="card"><span>${k}</span><strong>${s?.[k]??'—'}</strong></div>`).join('');document.getElementById('results').textContent=JSON.stringify(s,null,2)}async function get(){const r=await fetch(statusUrl,{headers:{Accept:'application/json'}});const j=await r.json();render(j);return j}async function next(){const r=await fetch(runUrl,{method:'POST',headers:{Accept:'application/json','Content-Type':'application/json','X-CSRF-TOKEN':csrf,'X-Requested-With':'XMLHttpRequest'},body:'{}'});return r.json()}async function loop(){const s=await get();if(s.status==='running'&&s.remaining>0){setTimeout(async()=>{await next();loop()},Math.max(0,Number(s.retry_after_seconds||s.delay_seconds||2))*1000)}}document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',()=>setTimeout(loop,1000)));loop();})();</script>
</body></html>
