<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Jarek eBay — fetch/cache runner</title>
<style>body{font:14px system-ui;margin:2rem;max-width:1200px}button,input,select{padding:.55rem;margin:.2rem}pre{background:#111;color:#eee;padding:1rem;overflow:auto}.warning{color:#9b3b00}.grid{display:grid;grid-template-columns:repeat(4,minmax(150px,1fr));gap:.5rem}.metric{border:1px solid #ddd;padding:.7rem}</style></head><body>
<h1>Jarek Gearboxes — eBay price fetch/cache</h1><p class="warning"><strong>Bezpieczny zakres:</strong> wyłącznie GET ofert eBay oraz opcjonalny lokalny cache. Nigdy revise/update/publish; marketplace_write=false.</p>
<label>Tryb <select id="mode"><option value="cache">Fetch + cache</option><option value="dry">Dry-run (bez zapisu)</option></select></label>
<label>Batch <input id="limit" type="number" min="1" max="100" value="50"></label><label>Delay ms <input id="delay" type="number" min="1500" max="10000" value="2000"></label><label>Offset <input id="offset" type="number" min="0" value="0"></label>
<p><button id="start">Start</button><button id="pause">Pause</button><button id="resume">Resume</button><button id="stop">Stop</button></p>
<div class="grid" id="metrics"></div><h2>Ostatni batch</h2><pre id="last">—</pre><h2>Przykładowe błędy</h2><pre id="errors">—</pre>
<script>
const $=id=>document.getElementById(id), state={running:false,paused:false,stopped:false,processed:0,fetched:0,cached:0,missing:0,stale:0,skipped:0,errors:0,retries:0,total:0,withOffer:0}, sleep=ms=>new Promise(r=>setTimeout(r,ms)); let aborter;
function draw(next){const remaining=Math.max(0,state.withOffer-next), names={total:'total_jarek_products',withOffer:'products_with_ebay_offer_id',processed:'processed',fetched:'fetched_count',cached:'cached_count',missing:'missing_price_count',stale:'stale_404_count',skipped:'skipped_count',errors:'errors_count'}; $('metrics').innerHTML=Object.entries(names).map(([k,n])=>`<div class="metric"><b>${n}</b><br>${state[k]}</div>`).join('')+`<div class="metric"><b>current_offset</b><br>${$('offset').value}</div><div class="metric"><b>next_offset</b><br>${next}</div><div class="metric"><b>estimated remaining</b><br>${remaining}</div>`}
async function request(url,options){for(let n=0;n<3;n++){aborter=new AbortController(); const timer=setTimeout(()=>aborter.abort(),30000); try{const r=await fetch(url,{...options,signal:aborter.signal});clearTimeout(timer);if([401,403].includes(r.status)){state.paused=true;throw new Error('Problem autoryzacji — runner zatrzymany.');}if(r.status>=500&&n<2){await sleep(1000*(n+1));continue}const json=await r.json();if(!r.ok)throw new Error(json.message||json.error||`HTTP ${r.status}`);return json}catch(e){clearTimeout(timer);if(n===2||state.paused||state.stopped)throw e;await sleep(1000*(n+1))}}}
async function run(){if(state.running)return;state.running=true;state.paused=false;state.stopped=false;try{while(!state.stopped){if(state.paused){await sleep(250);continue}const offset=+$('offset').value,limit=Math.min(100,Math.max(1,+$('limit').value));const dry=$('mode').value==='dry';const url=dry?`{{ route('admin.tools.jarek-gearboxes.ebay-price-fetch-preview') }}?channel=ebay_de&limit=${limit}&offset=${offset}`:`{{ route('admin.tools.jarek-gearboxes.ebay-price-fetch-cache-apply') }}`;const options=dry?{}:{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({channel:'ebay_de',limit,offset,confirm:'FETCH_JAREK_EBAY_PRICES_READ_ONLY_CACHE'})};const j=await request(url,options);$('last').textContent=JSON.stringify(j,null,2);state.total=j.total_jarek_products;state.withOffer=j.products_with_ebay_offer_id;state.processed+=j.count;state.fetched+=j.prices_fetched_from_ebay_count;state.cached+=dry?0:j.prices_fetched_from_ebay_count;state.missing+=j.prices_missing_count;state.stale+=j.stale_404_count;state.skipped+=j.count-j.eligible_for_7_percent_increase;state.errors+=j.products.filter(x=>x.http_status>=400&&x.http_status!==404).length;$('errors').textContent=JSON.stringify(j.products.filter(x=>x.ebay_error).slice(0,10),null,2);const next=j.next_offset;$('offset').value=next;draw(next);if(!j.count||next>=state.withOffer)break;await sleep(Math.max(1500,+$('delay').value))}}catch(e){$('errors').textContent=e.message}finally{state.running=false}}
$('start').onclick=run;$('pause').onclick=()=>state.paused=true;$('resume').onclick=()=>{state.paused=false;run()};$('stop').onclick=()=>{state.stopped=true;aborter?.abort()};draw(0);
</script></body></html>
