<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Jarek eBay price apply runner</title>
<style>body{font:15px system-ui;max-width:1200px;margin:30px auto;padding:0 20px}.danger{background:#fee2e2;border:2px solid #dc2626;padding:16px}.controls{display:flex;gap:10px;flex-wrap:wrap;margin:20px 0}input{padding:8px}button{padding:8px 15px}table{border-collapse:collapse;width:100%}td,th{padding:7px;border:1px solid #ddd;text-align:left}pre{background:#111;color:#eee;padding:15px;overflow:auto}.marketplace{font-size:20px;color:#b91c1c;font-weight:bold}</style></head><body>
<h1>Jarek Gearboxes — eBay DE +7% batch apply runner</h1>
<div class="danger"><div class="marketplace">⚠ MARKETPLACE WRITE</div><b>Wyłącznie price-only PUT istniejącej oferty.</b> Runner nie zmienia ceny lokalnej, stocku, quantity, treści, zdjęć, kategorii, polityk ani tytułów; nie publikuje i nie dotyka eBay FR. Wejście na stronę niczego nie uruchamia.</div>
<p>Global eBay write: <b>{{ ($ebayConnection['write_enabled'] ?? false) ? 'ENABLED' : 'DISABLED' }}</b></p>
<div class="controls"><button id="preview">Załaduj preview</button><label>Snapshot <input id="snapshot" size="68"></label><label>Batch (max 10) <input id="size" type="number" min="1" max="10" value="5"></label><label>Delay ms <input id="delay" type="number" min="1000" value="4000"></label></div>
<label>Token <input id="token" size="55" autocomplete="off" placeholder="APPLY_JAREK_EBAY_PRICES_7_PERCENT_BATCH_RUNNER"></label>
<div class="controls"><button id="start">Start Canary / kontrolowany runner od offsetu 0</button><button id="pause">Pause</button><button id="resume">Resume</button><button id="stop">Stop</button><button id="status">Odśwież status</button></div>
<h2>Pierwsze 20 planowanych rekordów</h2><table><thead><tr><th>ID</th><th>SKU</th><th>Offer / listing</th><th>Cena eBay</th><th>Waluta</th></tr></thead><tbody id="items"><tr><td colspan="5">Najpierw załaduj preview. Start pozostaje ręczny.</td></tr></tbody></table>
<h2>Status / batch history</h2><pre id="output">Nie uruchomiono.</pre>
<script>
const $=id=>document.getElementById(id), endpoint=@json(route('admin.tools.jarek-gearboxes.ebay-bulk-price-increase-apply-runner.action')), statusUrl=@json(route('admin.tools.jarek-gearboxes.ebay-bulk-price-increase-apply-runner-status')); let timer=null;
async function post(action, extra={}){const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({action,...extra})});const j=await r.json();$('output').textContent=JSON.stringify(j,null,2);return j}
function cancel(){if(timer){clearTimeout(timer);timer=null}}
async function tick(){const j=await post('batch');if(j.status==='running')timer=setTimeout(tick,j.delay_ms);else cancel()}
$('preview').onclick=async()=>{const r=await fetch(@json(route('admin.tools.jarek-gearboxes.ebay-bulk-price-increase-preview')).'?percent=7&channel=ebay_de'),j=await r.json();$('snapshot').value=j.snapshot_id;$('items').innerHTML=j.eligible_products.slice(0,20).map(x=>`<tr><td>${x.jarek_gearbox_id}</td><td>${x.sku}</td><td>${x.ebay_offer_id}<br>${x.ebay_listing_id??''}</td><td>${x.old_price} → ${x.new_price}</td><td>${x.currency}</td></tr>`).join('');$('output').textContent=JSON.stringify({snapshot_id:j.snapshot_id,eligible:j.products_eligible_for_price_increase,source:j.price_source},null,2)};
$('start').onclick=async()=>{cancel();if(!confirm('Rozpocząć MARKETPLACE WRITE od offsetu 0?'))return;const j=await post('start',{confirm:$('token').value,snapshot_id:$('snapshot').value,percent:7,channel:'ebay_de',batch_size:+$('size').value,delay_ms:+$('delay').value});if(j.ok&&j.status==='running')timer=setTimeout(tick,j.delay_ms)};
$('pause').onclick=async()=>{cancel();await post('pause')}; $('stop').onclick=async()=>{cancel();await post('stop')}; $('resume').onclick=async()=>{cancel();const j=await post('resume');if(j.ok&&j.status==='running')timer=setTimeout(tick,j.delay_ms)};
$('status').onclick=async()=>{const r=await fetch(statusUrl+'?snapshot_id='+encodeURIComponent($('snapshot').value)),j=await r.json();$('output').textContent=JSON.stringify(j,null,2)};
</script></body></html>
