<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="csrf-token" content="{{ csrf_token() }}"><title>Jarek eBay — +7% canary</title><style>body{font:14px system-ui;margin:2rem;max-width:1300px}button,input{padding:.6rem;margin:.3rem}pre{background:#111;color:#eee;padding:1rem;overflow:auto}.danger{border:2px solid #b00;padding:1rem;color:#800}table{border-collapse:collapse;width:100%}td,th{border:1px solid #ddd;padding:.4rem}</style></head><body>
<h1>Jarek Gearboxes — +7% price-only canary</h1><div class="danger"><b>Marketplace write.</b> Zmieniane pole: wyłącznie <code>pricingSummary.price</code>. Maksymalnie 5 ofert; brak Run All i brak automatycznego kolejnego batcha. Stock, treść, zdjęcia, kategorie, polityki i lokalna cena pozostają bez zmian.</div>
<p><button id="preview">Preview</button> Snapshot <input id="snapshot" size="70" readonly> Limit <input id="limit" type="number" min="1" max="5" value="5"></p>
<p>Wpisz potwierdzenie <input id="confirm" size="45" autocomplete="off" placeholder="INCREASE_JAREK_EBAY_PRICES_7_PERCENT"><button id="canary" disabled>Start Canary</button><button id="stop">Stop</button></p>
<div id="summary"></div><table><thead><tr><th>ID</th><th>Title</th><th>offer/listing/SKU</th><th>Old → new</th><th>Currency</th><th>Status</th></tr></thead><tbody id="items"></tbody></table><h2>Wynik canary</h2><pre id="result">Nie uruchomiono.</pre>
<script>
const $=id=>document.getElementById(id);let data,controller;
$('preview').onclick=async()=>{const r=await fetch(`{{ route('admin.tools.jarek-gearboxes.ebay-bulk-price-increase-preview') }}?percent=7&channel=ebay_de`),j=await r.json();data=j;$('snapshot').value=j.snapshot_id;const rows=j.eligible_products.slice(0,5);$('summary').innerHTML=`<p><b>Eligible:</b> ${j.products_eligible_for_price_increase}; <b>old total:</b> ${j.total_old_price}; <b>new total:</b> ${j.total_new_price}; <b>difference:</b> ${j.total_difference}; <b>currency:</b> ${j.currency_summary.map(x=>x.currency).join(', ')}; <b>cache age:</b> per-item fetched_at; <b>snapshot:</b> ${j.snapshot_id}</p><p><b>Warnings:</b> canary only; snapshot drift or cache older than configured max age blocks apply.</p>`;$('items').innerHTML=rows.map(x=>`<tr><td>${x.jarek_gearbox_id}</td><td>${x.title??''}</td><td>${x.ebay_offer_id??''}<br>${x.ebay_listing_id??''}<br>${x.sku??''}</td><td>${x.current_ebay_price} → ${x.new_price}<br><small>${x.fetched_at??''}</small></td><td>${x.currency}</td><td>ready</td></tr>`).join('');$('canary').disabled=false};
$('canary').onclick=async()=>{if($('confirm').value!=='INCREASE_JAREK_EBAY_PRICES_7_PERCENT'){alert('Wpisz dokładny token potwierdzenia.');return}if(!confirm('Wykonać price-only canary (maks. 5) i zatrzymać się po wyniku?'))return;controller=new AbortController();$('canary').disabled=true;try{const r=await fetch(`{{ route('admin.tools.jarek-gearboxes.ebay-bulk-price-increase-apply') }}`,{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify({percent:7,channel:'ebay_de',limit:Math.min(5,+$('limit').value),snapshot_id:$('snapshot').value,confirm:$('confirm').value})});$('result').textContent=JSON.stringify(await r.json(),null,2)}catch(e){$('result').textContent=e.message}};
$('stop').onclick=()=>controller?.abort();
</script></body></html>
