<!doctype html>
<html lang="pl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Jarek Gearboxes eBay Publish Runner</title>
<style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#f6f7fb;color:#111827;margin:0;padding:24px}.wrap{max-width:1200px;margin:auto}.card{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:18px;box-shadow:0 1px 2px #0001}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.btn{border:0;border-radius:8px;padding:9px 13px;font-weight:700;cursor:pointer}.start{background:#16a34a;color:white}.pause{background:#f59e0b}.resume{background:#2563eb;color:white}.stop{background:#dc2626;color:white}.muted{color:#6b7280}.bar{height:16px;background:#e5e7eb;border-radius:99px;overflow:hidden}.bar>span{display:block;height:100%;background:#22c55e;width:0%}.kv{display:grid;grid-template-columns:160px 1fr;gap:6px;margin:12px 0}.log{height:240px;overflow:auto;background:#111827;color:#d1fae5;border-radius:8px;padding:10px;font:12px ui-monospace,monospace}.err{color:#b91c1c}input{border:1px solid #d1d5db;border-radius:8px;padding:7px;width:90px}table{width:100%;border-collapse:collapse;font-size:12px;margin-top:10px}th,td{border-bottom:1px solid #e5e7eb;padding:6px;text-align:left;vertical-align:top}.summary{white-space:pre-wrap;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:10px;max-height:260px;overflow:auto}</style>
</head>
<body><div class="wrap"><h1>Jarek Gearboxes eBay DE real publish runner</h1>
<p class="muted">Tryb startowy: batch size domyślnie 1, delay 10s. Real write jest możliwy wyłącznie z confirm tokenem w batch endpoint.</p>
<section class="card">
<label>Batch size <input class="limit" type="number" min="1" max="5" value="1"></label>
<label>Delay (s) <input class="delay" type="number" min="0" value="10"></label>
<div class="controls"><button class="btn start">START</button><button class="btn pause">PAUSE</button><button class="btn resume">RESUME</button><button class="btn stop">STOP</button></div>
<div class="kv"><b>Status</b><span class="status">idle</span><b>Progress</b><div class="bar"><span></span></div><b>Processed / total</b><span class="processed">0 / ?</span><b>Current offset</b><span class="offset">0</span><b>Error</b><span class="error err">—</span></div>
<h3>Live log</h3><pre class="log"></pre><h3>Final summary</h3><pre class="summary">{}</pre>
<h3>Ostatnie wyniki per SKU</h3><table><thead><tr><th>SKU</th><th>Status</th><th>Offer</th><th>Listing</th><th>Blockers</th><th>Warnings / Errors</th></tr></thead><tbody></tbody></table>
</section></div>
<script>
let state={status:'idle',offset:0,total:1507,processed:0,summary:{},last:[]};const $=s=>document.querySelector(s);function render(){let pct=state.total?Math.min(100,Math.round(state.processed/state.total*100)):0;$('.status').textContent=state.status;$('.processed').textContent=`${state.processed} / ${state.total||'?'}`;$('.offset').textContent=state.offset;$('.bar span').style.width=pct+'%';$('.error').textContent=state.error||'—';$('.summary').textContent=JSON.stringify(state.summary,null,2);$('tbody').innerHTML=state.last.slice(-25).map(i=>`<tr><td>${i.sku||''}</td><td>${i.status||''}</td><td>${i.offer_id||''}</td><td>${i.listing_id||''}</td><td>${(i.blockers||[]).join(', ')}</td><td>${[...(i.warnings||[]),...(i.errors||[])].map(x=>typeof x==='string'?x:JSON.stringify(x)).join(', ')}</td></tr>`).join('')}function log(m){let l=$('.log');l.textContent+=`[${new Date().toLocaleTimeString()}] ${m}\n`;l.scrollTop=l.scrollHeight}
async function tick(){if(state.status!=='running')return;let limit=Math.max(1,Math.min(5,parseInt($('.limit').value||1,10)));let params=new URLSearchParams({offset:state.offset,limit,confirm:'jarek-ebay-de-bulk-publish-ready',only_ready:'1',skip_blocked:'1',skip_existing:'1'});try{let res=await fetch('/admin/tools/jarek-gearboxes/publish-runner-batch?'+params,{method:'POST',headers:{Accept:'application/json'}});let data=await res.json();if(!data.ok)throw new Error(data.error||((data.blockers||[]).join(', '))||'batch failed');let bs=data.batch_summary||{};state.processed+=bs.processed_count||0;state.offset=data.next_offset??state.offset;Object.keys(bs).forEach(k=>state.summary[k]=(state.summary[k]||0)+(k==='total'?0:(bs[k]||0)));state.summary.total=state.total;state.last=[...state.last,...(data.items||[])];log(`offset ${data.offset}, processed ${bs.processed_count||0}, published=${bs.published_count||0}, skipped=${bs.skipped_count||0}, blocked=${bs.blocked_count||0}, failed=${bs.failed_count||0}, next=${data.next_offset}, has_more=${data.has_more}`);render();if(data.has_more){setTimeout(tick, Math.max(0,parseInt($('.delay').value||10,10))*1000)}else{state.status='completed';log('completed');render()}}catch(e){state.status='error';state.error=e.message;log('ERROR '+e.message);render()}}
$('.start').onclick=()=>{state={status:'running',offset:0,total:1507,processed:0,summary:{},last:[]};$('.log').textContent='';log('start');render();tick()};$('.pause').onclick=()=>{if(state.status==='running'){state.status='paused';log('pause after current batch');render()}};$('.resume').onclick=()=>{if(['paused','error','idle'].includes(state.status)){state.status='running';log('resume');render();tick()}};$('.stop').onclick=()=>{state.status='idle';log('stop');render()};render();
</script></body></html>
