<!doctype html>
<html lang="pl">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<title>Jarek Gearboxes eBay Publish Runner</title>
<style>body{font-family:system-ui,-apple-system,Segoe UI,sans-serif;background:#f6f7fb;color:#111827;margin:0;padding:24px}.wrap{max-width:1200px;margin:auto}.card{background:white;border:1px solid #e5e7eb;border-radius:12px;padding:18px;box-shadow:0 1px 2px #0001}.controls{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.btn{border:0;border-radius:8px;padding:9px 13px;font-weight:700;cursor:pointer}.start{background:#16a34a;color:white}.pause{background:#f59e0b}.resume{background:#2563eb;color:white}.stop{background:#dc2626;color:white}.muted{color:#6b7280}.bar{height:16px;background:#e5e7eb;border-radius:99px;overflow:hidden}.bar>span{display:block;height:100%;background:#22c55e;width:0%}.kv{display:grid;grid-template-columns:160px 1fr;gap:6px;margin:12px 0}.log{height:240px;overflow:auto;background:#111827;color:#d1fae5;border-radius:8px;padding:10px;font:12px ui-monospace,monospace}.err{color:#b91c1c}input{border:1px solid #d1d5db;border-radius:8px;padding:7px;width:90px}table{width:100%;border-collapse:collapse;font-size:12px;margin-top:10px}th,td{border-bottom:1px solid #e5e7eb;padding:6px;text-align:left;vertical-align:top}.summary{white-space:pre-wrap;background:#f9fafb;border:1px solid #e5e7eb;border-radius:8px;padding:10px;max-height:260px;overflow:auto}</style>
</head>
<body><div class="wrap"><h1>Jarek Gearboxes eBay DE real publish runner</h1>
<p class="muted">Tryb bezpieczny: runner zawsze pobiera pierwsze aktualnie gotowe rekordy (offset=0), żeby nie przeskakiwać pozycji z dynamicznej listy missing_offer_id_only. Real write jest możliwy wyłącznie z confirm tokenem w batch endpoint.</p>
<section class="card">
<label>Batch size <input class="limit" type="number" min="1" max="100" value="3"></label>
<label>Delay (s) <input class="delay" type="number" min="0" value="10"></label>
<div class="controls"><button class="btn start">START</button><button class="btn pause">PAUSE</button><button class="btn resume">RESUME</button><button class="btn stop">STOP</button></div>
<div class="kv"><b>Status</b><span class="status">idle</span><b>Progress</b><div class="bar"><span></span></div><b>Processed / total</b><span class="processed">0 / ?</span><b>Request offset</b><span class="offset">0</span><b>Ready remaining</b><span class="remaining">?</span><b>Error</b><span class="error err">—</span></div>
<h3>Live log</h3><pre class="log"></pre><h3>Final summary</h3><pre class="summary">{}</pre>
<h3>Ostatnie wyniki per SKU</h3><table><thead><tr><th>SKU</th><th>Status</th><th>Offer</th><th>Listing</th><th>Blockers</th><th>Warnings / Errors</th></tr></thead><tbody></tbody></table>
</section></div>
<script>
const DEFAULT_OFFSET=0;
const DEFAULT_LIMIT=3;
const DEFAULT_DELAY=10;
let state={status:'idle',offset:0,total:0,processed:0,remaining:null,summary:{},last:[]};
const $=s=>document.querySelector(s);
function intInput(selector,fallback,min,max){let parsed=parseInt($(selector).value,10);if(Number.isNaN(parsed))parsed=fallback;parsed=Math.max(min,parsed);if(max!==undefined)parsed=Math.min(max,parsed);return parsed}
function syncOffsetInput(){ state.offset=0; }
function render(){let denom=state.processed+(state.remaining??0);let pct=denom?Math.min(100,Math.round(state.processed/denom*100)):0;$('.status').textContent=state.status;$('.processed').textContent=`${state.processed} / ${denom||'?'}`;$('.offset').textContent=state.offset;$('.remaining').textContent=state.remaining??'?';$('.bar span').style.width=pct+'%';$('.error').textContent=state.error||'—';$('.summary').textContent=JSON.stringify(state.summary,null,2);$('tbody').innerHTML=state.last.slice(-25).map(i=>`<tr><td>${i.sku||''}</td><td>${i.status||''}</td><td>${i.offer_id||''}</td><td>${i.listing_id||''}</td><td>${(i.blockers||[]).join(', ')}</td><td>${[...(i.warnings||[]),...(i.errors||[])].map(x=>typeof x==='string'?x:JSON.stringify(x)).join(', ')}</td></tr>`).join('')}
function log(m){let l=$('.log');l.textContent+=`[${new Date().toLocaleTimeString()}] ${m}\n`;l.scrollTop=l.scrollHeight}
function responseErrorMessage(data,res){if(res?.status===419)return 'CSRF/session expired or missing token. Refresh the page and start the runner again.';let diagnostics=data?.admin_diagnostics||{};return diagnostics.error_message||data?.error_message||data?.error||((data?.blockers||[]).join(', '))||'batch failed'}
async function readBatchJson(res){let text=await res.text();try{return text?JSON.parse(text):{ok:false,error:'Empty batch response',http_status:res.status,raw_response_preview:'',admin_diagnostics:{error_message:'Empty batch response'}}}catch(e){let preview=text.slice(0,500);return{ok:false,error:`Batch returned non-JSON HTTP ${res.status}`,http_status:res.status,raw_response_preview:preview,admin_diagnostics:{error_class:e.name,error_message:`Batch returned non-JSON response`,raw_response_preview:preview}}}}
function newRunState(){return{status:'running',offset:0,total:0,processed:0,remaining:null,summary:{},last:[]}}
function startRunner(label){let limit=intInput('.limit',DEFAULT_LIMIT,1,100);let delay=intInput('.delay',DEFAULT_DELAY,0);state=newRunState();$('.log').textContent='';log(`${label}: dynamic-list-safe offset=0, limit=${limit}, delay=${delay}s`);render();tick()}
async function tick(){if(state.status!=='running')return;let limit=intInput('.limit',DEFAULT_LIMIT,1,100);let requestOffset=0;state.offset=0;let params=new URLSearchParams({offset:'0',limit,confirm:'jarek-ebay-de-bulk-publish-ready',only_ready:'1',skip_blocked:'1',skip_existing:'1'});let url='/admin/tools/jarek-gearboxes/publish-runner-batch?'+params;log(`request ${url}`);try{let res=await fetch(url,{method:'GET',headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'},credentials:'same-origin'});let data=await readBatchJson(res);let bs=data.batch_summary||{};let errorMessage=responseErrorMessage(data,res);let logLine=`http_status=${res.status}, offset ${data.offset??requestOffset}, limit ${data.limit??limit}, processed ${bs.processed_count||0}, published=${bs.published_count||0}, skipped=${bs.skipped_count||0}, blocked=${bs.blocked_count||0}, failed=${bs.failed_count||0}, next_offset=${data.next_offset}, has_more=${data.has_more}`;if(!res.ok||!data.ok){state.status='error';state.error=errorMessage;let raw=data.raw_response_preview||data.admin_diagnostics?.raw_response_preview||'';log(`ERROR ${logLine}, raw_response_preview=${JSON.stringify(raw)}, error_message=${errorMessage}`);render();return}state.processed+=bs.processed_count||0;state.offset=0;state.remaining=data.ready_remaining_count??bs.ready_remaining_count??state.remaining;syncOffsetInput();Object.keys(bs).forEach(k=>state.summary[k]=(state.summary[k]||0)+(k==='total'?0:(bs[k]||0)));state.summary.ready_remaining_count=state.remaining;state.summary.published_total_count=data.published_total_count??bs.published_total_count??state.summary.published_total_count;state.last=[...state.last,...(data.items||[])];log(`${logLine}, ready_remaining=${data.ready_remaining_count??'?'}, completed=${data.completed??false}`);render();if(data.has_more&&!data.completed){setTimeout(tick, intInput('.delay',DEFAULT_DELAY,0)*1000)}else{state.status='completed';log('completed');render()}}catch(e){state.status='error';state.error=e.message;log(`ERROR offset ${state.offset}, limit ${limit}, http_status=fetch_failed, raw_response_preview=, error_message=${e.message}`);render()}}
$('.start').onclick=()=>startRunner('start');
$('.pause').onclick=()=>{if(state.status==='running'){state.status='paused';log('pause after current batch');render()}};
$('.resume').onclick=()=>{if(['paused','error','idle'].includes(state.status)){state.status='running';state.offset=0;log('resume with dynamic-list-safe offset=0');syncOffsetInput();render();tick()}};
$('.stop').onclick=()=>{state.status='idle';log('stop');render()};syncOffsetInput();render();
</script></body></html>
