<?php

namespace App\Services\Marketplace;

use App\Models\MarketplaceAccount;
use App\Models\MarketplaceCategory;
use App\Models\MarketplaceListing;
use App\Models\Part;
use App\Services\Marketplace\Api\AllegroApiClient;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Schema;

class AllegroPostPublishCompatibilityService
{
    public const META_PATH = 'marketplace_publish_results.allegro.compatibility';
    public const SOURCE = 'offer_suggestions';

    public function applyAfterPublish(Part $part, MarketplaceListing $listing, ?MarketplaceAccount $account = null): array
    {
        $offerId = trim((string) ($listing->external_offer_id ?: $listing->external_listing_id));
        $categoryId = $this->categoryId($part, $listing);
        $base = $this->meta('not_checked', $part, $listing, $offerId, $categoryId);
        if ($offerId === '') return $this->store($part, $listing, $base + ['status' => 'fetch_error', 'last_error' => 'missing_offer_id'], 'error', 'allegro_compatibility_suggestions');
        $account ??= $listing->account ?: MarketplaceAccount::query()->where('code', 'allegro_main')->first();
        if (! $account) return $this->store($part, $listing, $base + ['status' => 'fetch_error', 'last_error' => 'missing_allegro_account'], 'error', 'allegro_compatibility_suggestions');

        $client = new AllegroApiClient('allegro_main', $account);
        $config = $this->categoryConfig($client, $categoryId);
        if (($config['supported'] ?? null) === false) return $this->store($part, $listing, $base + $this->configFields($config) + ['status' => 'category_unsupported', 'warning' => 'category_not_supported'], 'skipped', 'allegro_compatibility_suggestions');

        try { $suggestions = $client->compatibilitySuggestionsByOfferId($offerId); }
        catch (\Throwable $e) { return $this->store($part, $listing, $base + ['status' => 'fetch_error', 'last_error' => $e->getMessage()], 'error', 'allegro_compatibility_suggestions'); }
        $items = $this->extractItems((array) ($suggestions['json'] ?? []));
        $returned = count($items);
        if (($suggestions['ok'] ?? false) !== true) {
            $status = (int) ($suggestions['http_status'] ?? 0) === 404 ? 'no_suggestions' : 'fetch_error';
            return $this->store($part, $listing, $base + $this->configFields($config) + ['status' => $status, 'returned_count' => 0, 'sent_count' => 0, 'http_status' => $suggestions['http_status'] ?? null, 'request_id' => $suggestions['request_id'] ?? null, 'last_error' => $status === 'fetch_error' ? 'suggestions_fetch_failed' : null], $status === 'fetch_error' ? 'error' : 'skipped', 'allegro_compatibility_suggestions');
        }
        if ($returned === 0) return $this->store($part, $listing, $base + $this->configFields($config) + ['status' => 'no_suggestions', 'returned_count' => 0, 'sent_count' => 0, 'http_status' => $suggestions['http_status'] ?? null, 'request_id' => $suggestions['request_id'] ?? null], 'skipped', 'allegro_compatibility_suggestions');

        $list = $this->normalizeList($items, $config); $hash = $this->hash($list); $sent = count($list['items']); $truncated = $returned > $sent;
        $found = $base + $this->configFields($config) + ['status' => 'suggestions_found', 'compatibilityList' => $list, 'returned_count' => $returned, 'sent_count' => $sent, 'truncated' => $truncated, 'canonical_hash' => $hash, 'fetched_at' => now()->toISOString(), 'request_id' => $suggestions['request_id'] ?? null, 'http_status' => $suggestions['http_status'] ?? null, 'warning' => $truncated ? 'allegro_compatibility_items_truncated_to_category_max_rows' : ($config['warning'] ?? null)];
        $this->store($part, $listing, $found, 'success', 'allegro_compatibility_suggestions');
        if ($sent === 0) return $this->store($part, $listing, $found + ['status' => 'no_suggestions'], 'skipped', 'allegro_compatibility_apply');
        $current = (array) data_get((array) $part->fresh()->review_metadata, self::META_PATH, []);
        if (($current['status'] ?? null) === 'confirmed' && ($current['offer_id'] ?? null) === $offerId && ($current['canonical_hash'] ?? null) === $hash) return $this->store($part, $listing, $found + ['status' => 'idempotent'], 'success', 'allegro_compatibility_apply');

        $lock = Cache::lock("allegro-compatibility:{$part->id}:{$offerId}:{$hash}", 120);
        if (! $lock->get()) return $this->store($part, $listing, $found + ['status' => 'apply_error', 'blocker' => 'compatibility_apply_locked', 'last_error' => 'parallel_apply_blocked'], 'error', 'allegro_compatibility_apply');
        try {
            $patch = $client->updateCompatibilityListOnly($offerId, $list);
            if (($patch['ok'] ?? false) !== true) return $this->store($part, $listing, $found + ['status' => 'apply_error', 'applied_at' => now()->toISOString(), 'last_error' => 'compatibility_patch_failed', 'http_status' => $patch['http_status'] ?? null, 'request_id' => $patch['request_id'] ?? null], 'error', 'allegro_compatibility_apply');
            $applied = $found + ['status' => 'applied_unverified', 'applied_at' => now()->toISOString(), 'http_status' => $patch['http_status'] ?? null, 'request_id' => $patch['request_id'] ?? null];
            $this->store($part, $listing, $applied, 'success', 'allegro_compatibility_apply');
            for ($i=0; $i<3; $i++) { if ($i>0) usleep(200000 * $i); $remote = $client->productOffer($offerId); $remoteList = (array) data_get($remote, 'json.compatibilityList', data_get($remote, 'body.compatibilityList', [])); $remoteHash = $remoteList ? $this->hash($this->normalizeList((array) ($remoteList['items'] ?? []), $config)) : null; if (($remote['ok'] ?? false) && $remoteHash === $hash) return $this->store($part, $listing, $applied + ['status' => 'confirmed', 'confirmed_at' => now()->toISOString(), 'confirmed_hash' => $remoteHash, 'request_id' => $remote['request_id'] ?? ($remote['response_summary']['request_id'] ?? null)], 'success', 'allegro_compatibility_confirm'); }
            return $this->store($part, $listing, $applied + ['status' => 'applied_unverified', 'warning' => 'read_after_write_not_confirmed'], 'warning', 'allegro_compatibility_confirm');
        } finally { optional($lock)->release(); }
    }

    public function audit(Part $part): array { $listing=$this->activeListing($part); $meta=(array)data_get((array)$part->review_metadata,self::META_PATH,[]); $offer=$listing?->external_offer_id ?: $listing?->external_listing_id; return ['read_only'=>true,'no_mutation'=>true,'marketplace_write'=>false,'external_requests'=>false,'part_id'=>$part->id,'active_allegro_listing'=>$listing?->only(['id','status','external_offer_id','external_listing_id','url']),'offer_id'=>$offer,'category_id'=>$this->categoryId($part,$listing),'local_metadata'=>$meta,'status'=>$meta['status']??'not_checked','item_count'=>count((array)data_get($meta,'compatibilityList.items',[])),'canonical_hash'=>$meta['canonical_hash']??null,'last_error'=>$meta['last_error']??null,'can_fetch_suggestions_by_offer_id'=>filled($offer),'fallback_behavior'=>'offer_remains_active_without_compatibility']; }
    public function preview(Part $part): array { $listing=$this->activeListing($part); $offer=trim((string)($listing?->external_offer_id ?: $listing?->external_listing_id)); $category=$this->categoryId($part,$listing); $base=['read_only'=>true,'no_mutation'=>true,'marketplace_write'=>false,'external_requests'=>true,'external_request_methods'=>['GET'],'offer_id'=>$offer?:null,'category_id'=>$category?:null,'endpoint'=>'GET /sale/compatibility-list-suggestions?offer.id={offerId}','fallback_behavior'=>'offer_remains_active_without_compatibility']; if($offer==='') return $base+['blockers'=>['missing_offer_id']]; $account=$listing?->account ?: MarketplaceAccount::query()->where('code','allegro_main')->first(); if(!$account) return $base+['blockers'=>['missing_allegro_account']]; $client=new AllegroApiClient('allegro_main',$account); $config=$this->categoryConfig($client,$category); $r=$client->compatibilitySuggestionsByOfferId($offer); $items=$this->extractItems((array)($r['json']??[])); $list=$this->normalizeList($items,$config); return $base+$this->configFields($config)+['http_status'=>$r['http_status']??null,'request_id'=>$r['request_id']??null,'returned_items'=>$items,'returned_count'=>count($items),'deduplicated_count'=>count($list['items']),'planned_sent_count'=>count($list['items']),'truncated'=>count($items)>count($list['items']),'planned_compatibilityList'=>$list,'planned_canonical_hash'=>$this->hash($list),'blockers'=>($config['supported']??true)===false?['category_unsupported']:[]]; }

    public function normalizeList(array $items,array $config=[]): array { $out=[];$seen=[];$max=$config['max_rows']??count($items); foreach($items as $item){ if(!is_array($item))continue; $n=$this->canonicalize($item,$config); if($n===[])continue; $key=json_encode($n,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES); if(isset($seen[$key]))continue; $seen[$key]=true; $out[]=$n; if($max!==null&&count($out)>=(int)$max)break;} return ['type'=>'MANUAL','items'=>$out]; }
    public function hash(array $list): string { return hash('sha256', json_encode($list, JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES)); }
    private function canonicalize(array $item,array $config=[]): array { $type=strtoupper((string)($item['type']??'')); $add=array_key_exists('additionalInfo',$item)?['additionalInfo'=>$item['additionalInfo']]:[]; if($type==='ID'&&filled($item['id']??null))return ['type'=>'ID','id'=>(string)$item['id']]+$add; if($type==='TEXT'&&filled($item['text']??null)){ $text=(string)$item['text']; if(isset($config['max_characters_per_line']))$text=mb_substr($text,0,(int)$config['max_characters_per_line']); return ['type'=>'TEXT','text'=>$text]+$add;} return []; }
    private function extractItems(array $json): array { $items=data_get($json,'compatibilityList.items',data_get($json,'items',[])); return array_values(array_filter(is_array($items)?$items:[],'is_array')); }
    private function categoryConfig(AllegroApiClient $client,string $id): array { if($id==='')return ['supported'=>null,'warning'=>'missing_category_id']; $r=Cache::remember('allegro_compatibility_supported_categories', now()->addHours(12), fn()=>$client->supportedCompatibilityCategories()); if(($r['ok']??false)!==true)return ['supported'=>null,'warning'=>'supported_categories_fetch_failed']; $rows=(array)(($r['json']['categories']??$r['json']['supportedCategories']??(array_is_list($r['json']??[])?$r['json']:[]))); foreach($this->categoryAndAncestors($id) as $candidate)foreach($rows as $row){$rowId=(string)data_get($row,'id',data_get($row,'category.id',data_get($row,'categoryId',''))); if($rowId===$candidate)return ['supported'=>true,'matched_category_id'=>$rowId,'input_type'=>data_get($row,'inputType'),'items_type'=>data_get($row,'itemsType'),'max_rows'=>is_numeric(data_get($row,'validationRules.maxRows'))?(int)data_get($row,'validationRules.maxRows'):null,'max_characters_per_line'=>is_numeric(data_get($row,'validationRules.maxCharactersPerLine'))?(int)data_get($row,'validationRules.maxCharactersPerLine'):null];} return ['supported'=>false]; }
    private function categoryAndAncestors(string $id): array { $ids=[$id]; if(!Schema::hasTable('marketplace_categories'))return $ids; $cat=MarketplaceCategory::where('channel','allegro_main')->where('external_category_id',$id)->first(); for($i=0;$cat&&filled($cat->parent_external_category_id)&&$i<20;$i++){ $ids[]=(string)$cat->parent_external_category_id; $cat=MarketplaceCategory::where('channel','allegro_main')->where('external_category_id',(string)$cat->parent_external_category_id)->first(); } return array_values(array_unique($ids)); }
    private function activeListing(Part $part): ?MarketplaceListing { return MarketplaceListing::where('part_id',$part->id)->where('marketplace','allegro')->whereNotIn('status',['ended','failed','deleted','archived'])->latest('id')->first(); }
    private function categoryId(Part $part, ?MarketplaceListing $listing): string { return trim((string)(data_get($listing?->raw_payload,'request_summary.category_id') ?: data_get($part->review_metadata,'marketplace_prepare_results.allegro.payload.category_id') ?: data_get($part->review_metadata,'marketplace_prepare_results.allegro.category_id'))); }
    private function meta(string $status,Part $part,MarketplaceListing $listing,string $offer,string $cat): array { return ['status'=>$status,'source'=>self::SOURCE,'offer_id'=>$offer?:null,'category_id'=>$cat?:null,'compatibilityList'=>['type'=>'MANUAL','items'=>[]],'returned_count'=>0,'sent_count'=>0,'truncated'=>false,'canonical_hash'=>null,'fetched_at'=>null,'applied_at'=>null,'confirmed_at'=>null,'last_error'=>null,'request_id'=>null,'warning'=>null]; }
    private function configFields(array $c): array { return ['input_type'=>$c['input_type']??null,'items_type'=>$c['items_type']??null,'max_rows'=>$c['max_rows']??null,'max_characters_per_line'=>$c['max_characters_per_line']??null]; }
    private function store(Part $part,MarketplaceListing $listing,array $meta,string $logStatus,string $action): array { $m=is_array($part->review_metadata)?$part->review_metadata:[]; data_set($m,self::META_PATH,$meta); $part->forceFill(['review_metadata'=>$m])->save(); app(ApiIntegrationLogger::class)->record(['marketplace'=>'allegro','action'=>$action,'status'=>$logStatus,'part_id'=>$part->id,'marketplace_listing_id'=>$listing->id,'external_id'=>$meta['offer_id']??null,'http_status'=>$meta['http_status']??null,'request_id'=>$meta['request_id']??null,'message'=>'Allegro post-publish compatibility '.$meta['status'],'offer_id'=>$meta['offer_id']??null,'category_id'=>$meta['category_id']??null,'source'=>self::SOURCE,'returned_count'=>$meta['returned_count']??0,'sent_count'=>$meta['sent_count']??0,'canonical_hash'=>$meta['canonical_hash']??null,'endpoint'=>$action==='allegro_compatibility_apply'?'PATCH /sale/product-offers/{offerId}':($action==='allegro_compatibility_confirm'?'GET /sale/product-offers/{offerId}':'GET /sale/compatibility-list-suggestions?offer.id={offerId}'),'request'=>['summary'=>$action==='allegro_compatibility_apply'?['payload_keys'=>['compatibilityList']]:['method'=>'GET']],'response'=>['summary'=>['status'=>$meta['status']??null]],'read_after_write'=>$action==='allegro_compatibility_confirm','confirmed_hash'=>$meta['confirmed_hash']??null,'final_success'=>in_array($meta['status']??null,['confirmed','idempotent'],true),'blocker'=>$meta['blocker']??null,'warning'=>$meta['warning']??null,'error'=>$meta['last_error']??null]); return ['ok'=>true,'compatibility'=>$meta,'message'=>$this->message($meta)]; }
    public function message(array $m): string { return match($m['status']??'') {'confirmed'=>'Oferta została wystawiona, a Allegro dodało sekcję Pasuje do dla '.(int)($m['sent_count']??0).' pojazdów.','no_suggestions'=>'Oferta została wystawiona bez sekcji Pasuje do — Allegro nie zwróciło sugestii.','category_unsupported'=>'Oferta została wystawiona. Ta kategoria nie obsługuje sekcji Pasuje do.','fetch_error'=>'Oferta została wystawiona, ale nie udało się pobrać sekcji Pasuje do.','apply_error'=>'Oferta została wystawiona, ale nie udało się dodać sekcji Pasuje do.','applied_unverified'=>'Oferta została wystawiona, a lista Pasuje do została wysłana, lecz oczekuje na potwierdzenie.','idempotent'=>'Oferta została wystawiona z wcześniej potwierdzoną sekcją Pasuje do.',default=>'Oferta została wystawiona.'}; }
}
