@extends('layouts.storefront')
@section('content')
@php
    $mainImage = $part->primaryImage();
    $mainSrc = $mainImage?->publicUrl();
@endphp
<div class="sf-container sf-page gp-product-page" id="product-{{ $part->id }}">@include('storefront.partials.breadcrumbs')<div class="sf-product-detail"><section class="sf-gallery"><div class="sf-gallery__main">@if($mainSrc)<img src="{{ $mainSrc }}" alt="{{ $mainImage->alt_text ?: $part->name }}">@else<span>GPSwiss<br>brak zdjęcia</span>@endif</div>@if($part->images->count() > 1)<div class="sf-thumbs">@foreach($part->images as $image) @php($thumbSrc = $image->publicUrl()) @if($thumbSrc)<img src="{{ $thumbSrc }}" alt="{{ $image->alt_text ?: $part->name }}" loading="lazy">@endif @endforeach</div>@endif</section><section class="sf-info-card"><h1>{{ $part->name }}</h1><p><strong>Numer części:</strong> {{ $part->part_number ?: $part->sku ?: '—' }}</p><p><strong>Stan:</strong> Używany / sprawdzony</p>@if($part->car_id)<a class="sf-link-box" href="{{ route('storefront.catalog', ['vehicle_model'=>trim(($part->car?->make ?? '').' '.($part->car?->model ?? ''))]) }}">Pokaż więcej części z tego pojazdu</a>@endif@if($part->short_description)<div>{!! nl2br(e($part->short_description)) !!}</div>@endif<div class="sf-trust"><span>Czas dostawy</span><span>Metody płatności</span><span>Zwrot do 14 dni zgodnie z regulaminem</span></div></section><aside class="sf-purchase"><span>Cena produktu</span><strong>{{ number_format((float)$part->price,2,',',' ') }} {{ $part->currency ?: 'PLN' }}</strong><p>Cena brutto. Najniższa cena z 30 dni dostępna przy finalizacji zamówienia.</p><button disabled>Dodaj do koszyka</button><a href="mailto:biuro@gpswiss.pl">Masz pytanie? Skontaktuj się</a><small>Pomagamy w doborze części po numerze VIN / OEM.</small></aside></div><div class="sf-tabs"><section><h2>Opis</h2><p>{!! nl2br(e($part->description ?: 'Opis produktu zostanie uzupełniony po imporcie danych.')) !!}</p></section><section><h2>Dane techniczne</h2><dl><dt>SKU</dt><dd>{{ $part->sku ?: '—' }}</dd><dt>OEM</dt><dd>{{ $part->oem_number ?: '—' }}</dd><dt>Kod producenta</dt><dd>{{ $part->manufacturer_code ?: '—' }}</dd></dl></section><section><h2>Kompatybilność</h2><p>Skontaktuj się z nami, aby potwierdzić kompatybilność po VIN/OEM.</p></section><section><h2>Gwarancja rozruchowa</h2><p>Każda część używana jest sprawdzana przed sprzedażą. Szczegóły zwrotów zgodnie z regulaminem.</p></section><section><h2>Sprzedawca</h2><p>GP Gregor Swiss - specjalistyczny dostawca używanych części samochodowych.</p></section></div>@if($related->isNotEmpty())<section class="sf-section"><div class="sf-section__head"><h2>Więcej części z tego pojazdu</h2></div><div class="sf-grid sf-grid--4">@foreach($related as $part) @include('storefront.partials.product-card', ['part'=>$part]) @endforeach</div></section>@endif</div>

@endsection
