<!doctype html>
<html lang="pl">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>eBay DE preview części #{{ $part->id }}</title>
    <style>
        body{font-family:ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f8fafc;color:#0f172a;margin:0;padding:24px} .wrap{max-width:1180px;margin:0 auto}.card{background:#fff;border:1px solid #e2e8f0;border-radius:12px;padding:18px;margin:14px 0;box-shadow:0 1px 2px rgba(15,23,42,.04)}.notice{border-left:5px solid #2563eb;background:#eff6ff}.warn{border-left:5px solid #d97706;background:#fffbeb}.bad{border-left:5px solid #dc2626;background:#fef2f2}h1{font-size:28px;margin:0 0 8px}h2{font-size:20px;margin:0 0 12px}code,pre{background:#f1f5f9;border-radius:8px}pre{padding:12px;overflow:auto}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(260px,1fr));gap:12px}.muted{color:#64748b}.images{display:flex;gap:12px;flex-wrap:wrap}.thumb{width:150px;border:1px solid #e2e8f0;border-radius:10px;padding:8px;background:#fff}.thumb img{width:100%;height:110px;object-fit:cover;border-radius:8px}.asset-thumb{width:72px;height:54px;object-fit:contain;border:1px solid #e2e8f0;border-radius:8px;background:#fff}.badge{display:inline-block;font-size:12px;padding:2px 7px;border-radius:999px;background:#dbeafe;color:#1e40af;margin:2px 0}table{width:100%;border-collapse:collapse}td,th{padding:8px;border-top:1px solid #e2e8f0;text-align:left;vertical-align:top}iframe{width:100%;height:680px;border:1px solid #cbd5e1;border-radius:10px;background:#fff}.small{font-size:13px}.break{word-break:break-all}</style>
</head>
<body><main class="wrap">
    <h1>Tymczasowy podgląd eBay DE — część #{{ $part->id }}</h1>
    <div class="card notice"><strong>Tymczasowy podgląd techniczny.</strong> Podgląd pokazuje treść wysyłaną do eBay DE. Nic nie jest publikowane. Wygląd na eBay może minimalnie różnić się po publikacji.<br><span class="muted">URL: {{ $url }}</span></div>
    @unless($preparedReady)<div class="card bad">Najpierw przygotuj aukcję eBay DE.</div>@endunless
    @if($missingImages)<div class="card bad">Brak publicznych zdjęć do podglądu aukcji eBay.</div>@endif
    @if($assetUrlWarning)<div class="card warn">Część obrazków szablonu może się nie wyświetlać. Szczegóły poniżej.</div>@endif

    <section class="card"><h2>1. Tytuł aukcji</h2><p>{{ $title['value'] }}</p><p class="muted small">Źródło: {{ $title['source'] }}</p></section>
    <section class="card"><h2>2. Product description</h2><p style="white-space:pre-wrap">{{ $description['value'] }}</p><p class="muted small">Długość: {{ $description['length'] }} znaków · Źródło: {{ $description['source'] }}</p></section>
    <section class="card"><h2>3. Opis HTML aukcji (offer.listingDescription)</h2><iframe referrerpolicy="no-referrer" srcdoc="{{ $listingDescriptionPreviewHtml }}"></iframe><details><summary>HTML źródłowy</summary><pre>{{ $listingDescription }}</pre></details></section>
    <section class="card"><h2>4. Zdjęcia części (product.imageUrls)</h2><p class="muted">main_image_preserved_as_first: {{ data_get($images, 'diagnostics.main_image_preserved_as_first') ? 'true' : 'false' }}</p><div class="images">@foreach($images['selected'] as $i => $image)<div class="thumb"><img src="{{ $image['selected_image_url'] }}" alt=""><span class="badge">{{ $i === 0 ? 'GŁÓWNE' : 'zdjęcie '.($i+1) }}</span><div class="small">Wariant: {{ $image['selected_image_variant'] }}</div><div class="small muted break">{{ $image['selected_image_url'] }}</div></div>@endforeach</div><details><summary>Lista imageUrls i diagnostyka</summary><pre>{{ json_encode(['imageUrls' => $images['urls'], 'diagnostics' => $images['diagnostics']], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre></details></section>
    <section class="card"><h2>5. Assety PNG szablonu eBay</h2><table><thead><tr><th>key</th><th>filename</th><th>selected source path</th><th>selected source variant</th><th>generated URL</th><th>miniatura admin HTML</th><th>HTTPS</th><th>source exists</th><th>HTTP check</th></tr></thead><tbody>@foreach($assetDiagnostics as $asset)<tr><td>{{ $asset['key'] }}</td><td>{{ $asset['filename'] }}</td><td class="break">{{ $asset['selected_source_path'] }}</td><td>{{ $asset['selected_source_variant'] }}</td><td class="break">{{ $asset['generated_url'] }}</td><td>@if($asset['generated_url'] !== '')<img class="asset-thumb" src="{{ $asset['generated_url'] }}" alt="{{ $asset['key'] }}">@else<span class="muted">brak URL</span>@endif</td><td>{{ $asset['absolute_https'] ? 'tak' : 'nie' }}</td><td>{{ $asset['source_exists'] ? 'tak' : 'nie' }}</td><td><pre>{{ json_encode($asset['http_check'], JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre></td></tr>@endforeach</tbody></table></section>
    <section class="card"><h2>6. Informacje diagnostyczne</h2><div class="grid"><pre>{{ json_encode($diagnostics, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre><pre>{{ json_encode(['inventory_item_payload' => $inventoryPayload, 'offer_payload' => $offerPayload], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE) }}</pre></div></section>
</main></body></html>
