<div style="max-width:1080px;margin:0 auto;background:#ffffff;color:#111827;font-family:Arial,Helvetica,sans-serif;border:1px solid #dbe3ef;border-radius:10px;overflow:hidden;box-shadow:0 10px 28px rgba(15,23,42,.08);">
  <div style="background:#f8fbff;border-bottom:1px solid #dbe3ef;">
    <table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tr>
      <td width="25%" align="center" style="padding:16px 12px;color:#06275d;font-weight:800;font-size:15px;border-right:1px solid #dbe3ef;"><img src="{{ $assets['icon_shipping'] }}" alt="{{ $labels['shipping'] }}" style="width:36px;height:auto;border:0;display:inline-block;vertical-align:middle;margin-right:8px;" />{{ $labels['shipping'] }}</td>
      <td width="25%" align="center" style="padding:16px 12px;color:#06275d;font-weight:800;font-size:15px;border-right:1px solid #dbe3ef;"><img src="{{ $assets['icon_returns'] }}" alt="{{ $labels['returns'] }}" style="width:36px;height:auto;border:0;display:inline-block;vertical-align:middle;margin-right:8px;" />{{ $labels['returns'] }}</td>
      <td width="25%" align="center" style="padding:16px 12px;color:#06275d;font-weight:800;font-size:15px;border-right:1px solid #dbe3ef;"><img src="{{ $assets['icon_packaging'] }}" alt="{{ $labels['packaging'] }}" style="width:36px;height:auto;border:0;display:inline-block;vertical-align:middle;margin-right:8px;" />{{ $labels['packaging'] }}</td>
      <td width="25%" align="center" style="padding:16px 12px;color:#06275d;font-weight:800;font-size:15px;"><img src="{{ $assets['icon_original'] }}" alt="{{ $labels['original'] }}" style="width:36px;height:auto;border:0;display:inline-block;vertical-align:middle;margin-right:8px;" />{{ $labels['original'] }}</td>
    </tr></table>
  </div>
  <div style="padding:32px 30px 28px;">
    <h1 style="margin:0;color:#06275d;font-size:38px;line-height:1.16;font-weight:900;letter-spacing:.3px;text-transform:uppercase;text-align:center;">{{ $title }}</h1>
    <div style="width:92px;height:4px;background:#0057d9;margin:14px auto 22px;border-radius:2px;"></div>
    @if(filled($translationFallbackNotice ?? null))<div style="border:1px solid #fbbf24;background:#fffbeb;color:#92400e;border-radius:8px;padding:12px 16px;margin:0 0 18px;text-align:center;font-weight:800;">{{ $translationFallbackNotice }}</div>@endif
    <div style="border:1px solid #dbe3ef;border-radius:8px;overflow:hidden;background:#ffffff;margin:0 0 22px;"><div style="background:#06275d;color:#ffffff;padding:15px 17px;font-size:18px;font-weight:900;letter-spacing:.2px;text-align:center;">{{ $labels['description'] }}</div><div style="padding:20px 22px;text-align:center;">{!! $descriptionBlock !!}</div></div>
    <div style="border:1px solid #dbe3ef;border-radius:8px;overflow:hidden;background:#ffffff;margin:0 0 22px;"><div style="background:#06275d;color:#ffffff;padding:15px 17px;font-size:18px;font-weight:900;letter-spacing:.2px;text-align:center;">{{ $labels['specifications'] }}</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;text-align:center;">{!! $specificationRows !!}</table></div>
    {!! $sameVehicleCta !!}
    <div style="border:1px solid #dbe3ef;background:#ffffff;margin:0 0 20px;border-radius:8px;overflow:hidden;box-shadow:0 8px 20px rgba(15,23,42,.05);"><div style="padding:30px 28px 24px;text-align:center;background:#ffffff;"><h2 style="margin:0 0 10px;color:#06275d;font-size:26px;line-height:1.2;font-weight:900;text-align:center;">{{ $labels['europe_delivery_title'] }}</h2><p style="margin:0 0 16px;color:#1f2937;font-size:16px;line-height:1.7;text-align:center;">{{ $labels['europe_delivery_text'] }}</p><div style="display:inline-block;background:#eaf2ff;border:1px solid #c9dcf8;color:#06275d;border-radius:6px;padding:12px 16px;font-size:16px;font-weight:900;">{{ $labels['delivery_time'] }}</div></div><img src="{{ $assets['europe_map'] }}" alt="{{ $labels['europe_delivery_title'] }}" style="width:100%;height:auto;border:0;display:block;margin:0;border-radius:0 0 8px 8px;" /></div>
    <div style="border:1px solid #dbe3ef;background:#f8fbff;margin:0 0 22px;border-radius:8px;padding:18px 20px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="border-collapse:collapse;"><tr><td width="50%" align="center" style="padding:0 10px 0 0;"><div style="background:#ffffff;border:1px solid #dbe3ef;border-radius:8px;padding:18px 12px;"><img src="{{ $assets['dhl_logo'] }}" alt="DHL" style="max-width:160px;height:auto;border:0;display:block;margin:0 auto;" /></div></td><td width="50%" align="center" style="padding:0 0 0 10px;"><div style="background:#ffffff;border:1px solid #dbe3ef;border-radius:8px;padding:18px 12px;"><img src="{{ $assets['dpd_logo'] }}" alt="DPD" style="max-width:160px;height:auto;border:0;display:block;margin:0 auto;" /></div></td></tr></table></div>
  </div>
  <div style="background:#06275d;color:#ffffff;text-align:center;padding:24px 24px;border-top:4px solid #0057d9;"><div style="font-size:23px;font-weight:900;margin-bottom:7px;letter-spacing:.3px;">{{ $labels['trust_title'] }}</div><div style="font-size:15px;font-weight:700;color:#dbeafe;">{{ $labels['trust_subtitle'] }}</div></div>
</div>
