<!doctype html><html lang="pl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Podgląd aukcji Allegro #{{ $part->id }}</title><style>body{font-family:system-ui;background:#f8fafc;color:#0f172a;margin:0}.wrap{max-width:1200px;margin:auto;padding:24px}.notice{background:#eff6ff;border:1px solid #bfdbfe;color:#1e40af;border-radius:12px;padding:14px;margin-bottom:16px;font-weight:700}.bad{background:#fff7ed;border-color:#fed7aa;color:#9a3412}.grid{display:grid;grid-template-columns:380px 1fr;gap:18px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:14px;padding:16px}.kv{display:grid;grid-template-columns:150px 1fr;gap:8px}.k{color:#64748b}.v{font-weight:600;overflow-wrap:anywhere}.pill{border-radius:999px;padding:3px 9px;font-size:12px;font-weight:700}.ok{background:#dcfce7;color:#166534}.warn{background:#fef3c7;color:#92400e}.images{display:flex;gap:8px;flex-wrap:wrap}.images img{width:92px;height:92px;object-fit:cover;border-radius:10px;border:1px solid #e2e8f0}pre{white-space:pre-wrap;background:#0f172a;color:#e2e8f0;padding:12px;border-radius:10px;font-size:12px;overflow:auto}table{width:100%;border-collapse:collapse}td,th{border-bottom:1px solid #e2e8f0;padding:7px;text-align:left}@media(max-width:900px){.grid{grid-template-columns:1fr}}</style></head><body><div class="wrap">
<div class="notice">To jest tylko podgląd. Nie wystawia oferty i nie wykonuje żadnego zapisu do Allegro.</div>
@if(!($readiness['can_prepare'] ?? false))<div class="notice bad">Aukcja nie jest gotowa. Poniżej widoczne są missing_fields, warnings i blockers.</div>@endif
<h1>Podgląd aukcji Allegro</h1><p>Część #{{ $part->id }} · read-only · <span class="pill ok">will_make_marketplace_request=false</span></p>
<div class="grid"><section class="card"><h2>Status i dane</h2><div class="kv">
<div class="k">Readiness</div><div class="v"><span class="pill {{ ($readiness['can_prepare'] ?? false) ? 'ok' : 'warn' }}">{{ ($readiness['can_prepare'] ?? false) ? 'gotowa' : 'niegotowa' }}</span></div>
<div class="k">can_prepare</div><div class="v">{{ ($readiness['can_prepare'] ?? false) ? 'true' : 'false' }}</div><div class="k">can_publish_later</div><div class="v">{{ ($readiness['can_publish_later'] ?? false) ? 'true' : 'false' }}</div>
<div class="k">Tytuł</div><div class="v">{{ $preview['title'] ?? '—' }}</div><div class="k">SKU / numer</div><div class="v">{{ $preview['sku'] ?: '—' }} / {{ $preview['part_number'] ?: '—' }}</div>
<div class="k">Cena PLN</div><div class="v">{{ $preview['price_pln'] ?? '—' }}</div><div class="k">Ilość</div><div class="v">{{ $preview['quantity'] }}</div><div class="k">Stan</div><div class="v">{{ $preview['condition'] }}</div>
<div class="k">Kategoria Allegro</div><div class="v">{{ $preview['category_id'] ?? '—' }}</div><div class="k">Lokalna kategoria</div><div class="v">{{ $preview['local_category'] ?? '—' }}</div><div class="k">Źródło mapowania</div><div class="v">{{ $preview['category_mapping_source'] ?? '—' }}</div>
</div><h2>Zdjęcia</h2><div class="images">@forelse($preview['image_urls'] as $url)<img src="{{ $url }}" alt="zdjęcie {{ $loop->iteration }}">@empty<span class="pill warn">brak</span>@endforelse</div>
<h2>Readiness</h2><strong>missing_fields</strong><ul>@forelse(($readiness['missing_fields'] ?? []) as $i)<li>{{ $i }}</li>@empty<li>brak</li>@endforelse</ul><strong>warnings</strong><ul>@forelse(($readiness['warnings'] ?? []) as $i)<li>{{ $i }}</li>@empty<li>brak</li>@endforelse</ul><strong>blockers</strong><ul>@forelse(($readiness['blockers'] ?? []) as $i)<li>{{ $i }}</li>@empty<li>brak</li>@endforelse</ul></section>
<section class="card"><h2>Opis Allegro / sekcje opisu</h2><pre>{{ $preview['description'] }}</pre><h2>Parametry Allegro</h2><p>Źródło definicji: <strong>{{ $preview['allegro_parameters']['parameter_definitions_source'] ?? 'none' }}</strong></p><h3>Product parameters (productSet.product.parameters)</h3><pre>{{ json_encode($preview['allegro_parameters']['allegro_product_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre><h3>Offer parameters (parameters)</h3><pre>{{ json_encode($preview['allegro_parameters']['allegro_offer_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre><h3>missing_required_parameters</h3><pre>{{ json_encode($preview['allegro_parameters']['missing_required_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre><h3>unmapped_parameters</h3><pre>{{ json_encode($preview['allegro_parameters']['unmapped_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre><h3>Źródła wartości</h3><pre>{{ json_encode($preview['allegro_parameters']['parameter_source_diagnostics'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) }}</pre></section></div></div></body></html>
