<!doctype html>
<html lang="pl">
<head><meta charset="utf-8"><title>Podgląd aukcji Allegro</title><style>body{font-family:Arial,sans-serif;margin:24px;color:#172033}.safe{background:#ecfdf5;border:1px solid #10b981;padding:12px;border-radius:8px}.warn{background:#fff7ed;border:1px solid #fb923c;padding:12px;border-radius:8px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{border:1px solid #d6dae1;border-radius:8px;padding:14px;margin-top:16px}pre{white-space:pre-wrap;background:#f8fafc;padding:12px;border-radius:8px;overflow:auto}.imgs img{max-width:120px;max-height:90px;margin:4px;border:1px solid #ddd}</style></head>
<body>
<h1>Podgląd aukcji Allegro</h1>
<div class="safe">To jest tylko podgląd. Nie wystawia oferty i nie wykonuje żadnego zapisu do Allegro. will_make_marketplace_request={{ ($preview['will_make_marketplace_request'] ?? true) ? 'true' : 'false' }}</div>
@if(($readiness['blockers'] ?? []) || ($readiness['warnings'] ?? []))<div class="warn"><strong>Aukcja nie jest gotowa, jeśli są blokery.</strong></div>@endif
<div class="grid">
<section class="card"><h2>Status readiness</h2><pre>{{ json_encode(['can_prepare'=>$readiness['ready'] ?? false,'can_publish_later'=>$readiness['ready'] ?? false,'missing_fields'=>$readiness['missing_fields'] ?? [],'warnings'=>$readiness['warnings'] ?? [],'blockers'=>$readiness['blockers'] ?? []], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></section>
<section class="card"><h2>Dane aukcji</h2><p><b>Tytuł:</b> {{ $preview['name'] ?? $preview['title'] ?? '' }}</p><p><b>SKU / numer części:</b> {{ $preview['sku'] ?? '' }} / {{ $preview['part_number'] ?? '' }}</p><p><b>Cena PLN:</b> {{ data_get($preview,'price.amount') }}</p><p><b>Ilość:</b> {{ $preview['quantity'] ?? data_get($preview,'stock.quantity') }}</p><p><b>Stan:</b> Używany</p><p><b>Kategoria Allegro:</b> {{ data_get($preview,'category.id') }}</p><p><b>Kategoria lokalna:</b> {{ data_get($preview,'category.local_path') }} ({{ data_get($preview,'category.local_id') }})</p><p><b>Źródło mapowania kategorii:</b> {{ $readiness['category']['marketplace_category_mapping_exists'] ?? false ? 'marketplace_category_mappings' : 'brak' }}</p></section>
</div>
<section class="card"><h2>Zdjęcia</h2><div class="imgs">@foreach(($preview['images'] ?? []) as $url)<img src="{{ $url }}" alt="image">@endforeach</div></section>
<section class="card"><h2>Opis Allegro / sekcje opisu</h2><pre>{{ $preview['description'] ?? '' }}</pre></section>
<section class="card"><h2>Parametry Allegro</h2><h3>Product parameters</h3><pre>{{ json_encode($preview['allegro_product_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><h3>Offer parameters</h3><pre>{{ json_encode($preview['allegro_offer_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><h3>missing_required_parameters</h3><pre>{{ json_encode($preview['missing_required_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><h3>unmapped_parameters</h3><pre>{{ json_encode($preview['unmapped_parameters'] ?? [], JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre><h3>Źródła wartości</h3><pre>{{ json_encode(data_get($preview,'allegro_parameters.parameter_source_diagnostics', []), JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE) }}</pre></section>
</body></html>
