@extends('layouts.storefront')
@section('content')
<div class="sf-container sf-page sf-account-page"><div class="sf-account-head"><h1>{{ __('storefront.account') }}</h1><form method="post" action="{{ route('storefront.logout') }}">@csrf<button class="sf-btn sf-btn--outline" type="submit">{{ __('storefront.logout_short') }}</button></form></div>
<div class="sf-account-grid"><section class="sf-static-card"><h2>{{ __('storefront.my_data') }}</h2><form method="post" action="{{ route('storefront.account.update') }}" class="sf-auth-form sf-auth-grid">@csrf @method('PATCH')
@foreach(['tax_id'=>__('storefront.tax_id'),'company_name'=>__('storefront.company_name'),'first_name'=>__('storefront.first_name'),'last_name'=>__('storefront.last_name'),'phone'=>__('storefront.phone'),'email'=>__('storefront.email')] as $name=>$label)
<label>{{ $label }}<input name="{{ $name }}" value="{{ old($name, $user->{$name}) }}" {{ in_array($name,['first_name','last_name','phone','email'])?'required':'' }}>@error($name)<small>{{ $message }}</small>@enderror</label>
@endforeach
<button class="sf-btn" type="submit">{{ __('storefront.save_data') }}</button></form></section>
<section class="sf-static-card" id="orders"><h2>{{ __('storefront.my_orders') }}</h2>@forelse($orders as $order)<article class="sf-order-card"><strong>{{ $order->external_reference ?: '#'.$order->id }}</strong><span>{{ optional($order->occurred_at ?: $order->created_at)->format('d.m.Y') }}</span><span>{{ __('storefront.status') }}: {{ data_get($order->payload,'status', $order->severityLabel()) }}</span><span>{{ __('storefront.sum') }}: {{ data_get($order->payload,'total', '—') }}</span><p>{{ $order->title }}</p></article>@empty<p>{{ __('storefront.no_orders_for_email', ['email' => $user->email]) }}</p>@endforelse</section>
<section class="sf-static-card"><h2>{{ __('storefront.returns') }}</h2><form method="post" action="{{ route('storefront.account.returns.store') }}" class="sf-auth-form">@csrf<label>{{ __('storefront.completed_order') }}<select name="order_id" required><option value="">{{ __('storefront.choose_order') }}</option>@foreach($returnableOrders as $order)<option value="{{ $order->id }}">{{ $order->external_reference ?: '#'.$order->id }} — {{ $order->title }}</option>@endforeach</select>@error('order_id')<small>{{ $message }}</small>@enderror</label><label>{{ __('storefront.return_reason') }}<input name="reason" required>@error('reason')<small>{{ $message }}</small>@enderror</label><label>{{ __('storefront.message_description') }}<textarea name="message" rows="4">{{ old('message') }}</textarea></label><button class="sf-btn" type="submit" @if($returnableOrders->isEmpty()) disabled @endif>{{ __('storefront.submit_return') }}</button>@if($returnableOrders->isEmpty())<p class="sf-muted">{{ __('storefront.return_after_completed') }}</p>@endif</form>@forelse($returns as $return)<article class="sf-order-card"><strong>{{ __('storefront.return_number', ['id' => $return->id]) }}</strong><span>{{ __('storefront.status') }}: {{ $return->status }}</span><p>{{ $return->reason }}</p></article>@empty<p>{{ __('storefront.no_returns') }}</p>@endforelse</section></div></div>
@endsection
