@extends('layouts.storefront')
@section('content')
<div class="sf-container sf-page sf-account-page"><div class="sf-account-head"><h1>Moje konto</h1><form method="post" action="{{ route('storefront.logout') }}">@csrf<button class="sf-btn sf-btn--outline" type="submit">Wyloguj</button></form></div>
<div class="sf-account-grid"><section class="sf-static-card"><h2>Moje dane</h2><form method="post" action="{{ route('storefront.account.update') }}" class="sf-auth-form sf-auth-grid">@csrf @method('PATCH')
@foreach(['tax_id'=>'NIP','company_name'=>'Nazwa firmy','first_name'=>'Imię','last_name'=>'Nazwisko','phone'=>'Numer telefonu','email'=>'Adres e-mail'] as $name=>$label)
<label>{{ $label }}<input name="{{ $name }}" value="{{ old($name, $user->{$name}) }}" {{ in_array($name,['first_name','last_name','phone','email'])?'required':'' }}>@error($name)<small>{{ $message }}</small>@enderror</label>
@endforeach
<button class="sf-btn" type="submit">Zapisz dane</button></form></section>
<section class="sf-static-card" id="orders"><h2>Moje zamówienia</h2>@forelse($orders as $order)<article class="sf-order-card"><strong>{{ $order->external_reference ?: '#'.$order->id }}</strong><span>{{ optional($order->occurred_at ?: $order->created_at)->format('d.m.Y') }}</span><span>Status: {{ data_get($order->payload,'status', $order->severityLabel()) }}</span><span>Suma: {{ data_get($order->payload,'total', '—') }}</span><p>{{ $order->title }}</p></article>@empty<p>Nie znaleźliśmy zamówień przypisanych do adresu {{ $user->email }}.</p>@endforelse</section>
<section class="sf-static-card"><h2>Zwroty</h2><form method="post" action="{{ route('storefront.account.returns.store') }}" class="sf-auth-form">@csrf<label>Zrealizowane zamówienie<select name="order_id" required><option value="">Wybierz zamówienie</option>@foreach($returnableOrders as $order)<option value="{{ $order->id }}">{{ $order->external_reference ?: '#'.$order->id }} — {{ $order->title }}</option>@endforeach</select>@error('order_id')<small>{{ $message }}</small>@enderror</label><label>Powód zwrotu<input name="reason" required>@error('reason')<small>{{ $message }}</small>@enderror</label><label>Wiadomość/opis<textarea name="message" rows="4">{{ old('message') }}</textarea></label><button class="sf-btn" type="submit" @if($returnableOrders->isEmpty()) disabled @endif>Zgłoś zwrot</button>@if($returnableOrders->isEmpty())<p class="sf-muted">Zwrot można zgłosić po zrealizowaniu zamówienia.</p>@endif</form>@forelse($returns as $return)<article class="sf-order-card"><strong>Zwrot #{{ $return->id }}</strong><span>Status: {{ $return->status }}</span><p>{{ $return->reason }}</p></article>@empty<p>Brak zgłoszonych zwrotów.</p>@endforelse</section></div></div>
@endsection
